// <auto-generated />
using System;
using Aethra.Modules.Proxy.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aethra.Modules.Proxy.Infrastructure.Migrations
{
    [DbContext(typeof(ProxyDbContext))]
    [Migration("20260610021312_RouteOperationalOwnerBackfill")]
    partial class RouteOperationalOwnerBackfill
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("proxy")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aethra.Modules.Proxy.Domain.AcmeAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<string>("AccountKeyPemCipherText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_key_pem");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("UseStaging")
                        .HasColumnType("boolean")
                        .HasColumnName("use_staging");

                    b.HasKey("Id");

                    b.ToTable("tls_account", "proxy");
                });

            modelBuilder.Entity("Aethra.Modules.Proxy.Domain.Certificate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("hostname");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NotAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_after");

                    b.Property<DateTimeOffset?>("NotBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_before");

                    b.Property<string>("PfxCipherText")
                        .HasColumnType("text")
                        .HasColumnName("pfx_cipher_text");

                    b.Property<DateTimeOffset?>("RenewAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("renew_after");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Hostname")
                        .IsUnique()
                        .HasDatabaseName("ux_certificates_hostname");

                    b.HasIndex("RenewAfter")
                        .HasDatabaseName("ix_certificates_renew_after");

                    b.ToTable("certificates", "proxy");
                });

            modelBuilder.Entity("Aethra.Modules.Proxy.Domain.Route", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("BackendUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("backend_url");

                    b.Property<string>("CertificateId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("certificate_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("hostname");

                    b.Property<string>("OperationalOwnerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("operational_owner_id");

                    b.Property<string>("OperationalOwnerType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("operational_owner_type");

                    b.Property<string>("Origin")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("origin");

                    b.Property<string>("PathPrefix")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasDefaultValue("/")
                        .HasColumnName("path_prefix");

                    b.Property<bool>("TlsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("tls_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Hostname", "PathPrefix")
                        .IsUnique()
                        .HasDatabaseName("ux_routes_hostname_path");

                    b.HasIndex("OperationalOwnerType", "OperationalOwnerId")
                        .HasDatabaseName("ix_routes_operational_owner");

                    b.ToTable("routes", "proxy");
                });

            modelBuilder.Entity("Aethra.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt", "NextAttemptAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("outbox_messages", "proxy");
                });
#pragma warning restore 612, 618
        }
    }
}
