// <auto-generated />
using System;
using Aethra.Modules.Services.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aethra.Modules.Services.Infrastructure.Migrations
{
    [DbContext(typeof(ServicesDbContext))]
    [Migration("20260603190101_F121_ScheduledJobs")]
    partial class F121_ScheduledJobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("services")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aethra.Modules.Services.Domain.ManagedService", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<byte[]>("AdminCredentialsCipher")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("admin_credentials_cipher");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("container_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<bool>("ExposedExternally")
                        .HasColumnType("boolean")
                        .HasColumnName("exposed_externally");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("image");

                    b.Property<int>("InternalPort")
                        .HasColumnType("integer")
                        .HasColumnName("internal_port");

                    b.Property<DateTimeOffset?>("LastBackupAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_backup_at");

                    b.Property<DateTimeOffset?>("LastRestoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_restored_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NetworkName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("network_name");

                    b.Property<DateTimeOffset?>("ProvisionedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("provisioned_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("TargetVmId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_vm_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_managed_services_slug");

                    b.ToTable("managed_services", "services");
                });

            modelBuilder.Entity("Aethra.Modules.Services.Domain.ScheduledJob", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("command");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cron_expression");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<int>("MaxConcurrent")
                        .HasColumnType("integer")
                        .HasColumnName("max_concurrent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("NextRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("service_id");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_scheduled_jobs_service");

                    b.HasIndex("Enabled", "NextRunAt")
                        .HasDatabaseName("ix_scheduled_jobs_due");

                    b.ToTable("scheduled_jobs", "services");
                });

            modelBuilder.Entity("Aethra.Modules.Services.Domain.ScheduledJobRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer")
                        .HasColumnName("exit_code");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("job_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Stderr")
                        .HasColumnType("text")
                        .HasColumnName("stderr");

                    b.Property<string>("Stdout")
                        .HasColumnType("text")
                        .HasColumnName("stdout");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "StartedAt")
                        .HasDatabaseName("ix_scheduled_job_runs_job_time");

                    b.ToTable("scheduled_job_runs", "services");
                });

            modelBuilder.Entity("Aethra.Modules.Services.Domain.ServiceBackup", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("destination_path");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("service_id");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_service_backups_service");

                    b.ToTable("service_backups", "services");
                });

            modelBuilder.Entity("Aethra.Modules.Services.Domain.ServiceBinding", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("CredentialsCipher")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("credentials_cipher");

                    b.Property<string>("InjectedEnvVarPrefix")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("injected_env_var_prefix");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("instance_id");

                    b.Property<DateTimeOffset?>("LastRotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_rotated_at");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("permissions");

                    b.Property<DateTimeOffset?>("ProvisionedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("provisioned_at");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("resource_name");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("service_id");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("InstanceId", "ServiceId")
                        .IsUnique()
                        .HasDatabaseName("ux_service_bindings_instance_service_active")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("service_bindings", "services");
                });

            modelBuilder.Entity("Aethra.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt", "NextAttemptAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("outbox_messages", "services");
                });

            modelBuilder.Entity("Aethra.Modules.Services.Domain.ManagedService", b =>
                {
                    b.OwnsOne("Aethra.Modules.Services.Domain.BackupPolicy", "BackupPolicy", b1 =>
                        {
                            b1.Property<string>("ManagedServiceId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("CronExpression")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("backup_cron");

                            b1.Property<string>("Destination")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("backup_destination");

                            b1.Property<int>("RetentionCount")
                                .HasColumnType("integer")
                                .HasColumnName("backup_retention");

                            b1.HasKey("ManagedServiceId");

                            b1.ToTable("managed_services", "services");

                            b1.WithOwner()
                                .HasForeignKey("ManagedServiceId");
                        });

                    b.Navigation("BackupPolicy");
                });

            modelBuilder.Entity("Aethra.Modules.Services.Domain.ScheduledJob", b =>
                {
                    b.HasOne("Aethra.Modules.Services.Domain.ManagedService", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aethra.Modules.Services.Domain.ScheduledJobRun", b =>
                {
                    b.HasOne("Aethra.Modules.Services.Domain.ScheduledJob", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aethra.Modules.Services.Domain.ServiceBinding", b =>
                {
                    b.HasOne("Aethra.Modules.Services.Domain.ManagedService", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Aethra.Modules.Services.Domain.MigrationsHook", "MigrationsHook", b1 =>
                        {
                            b1.Property<string>("ServiceBindingId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Command")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("migrations_hook_command");

                            b1.Property<bool>("FailDeployOnError")
                                .HasColumnType("boolean")
                                .HasColumnName("migrations_hook_fail_on_error");

                            b1.Property<string>("RunOn")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("migrations_hook_run_on");

                            b1.Property<int>("TimeoutSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("migrations_hook_timeout_seconds");

                            b1.HasKey("ServiceBindingId");

                            b1.ToTable("service_bindings", "services");

                            b1.WithOwner()
                                .HasForeignKey("ServiceBindingId");
                        });

                    b.Navigation("MigrationsHook");
                });
#pragma warning restore 612, 618
        }
    }
}
