// <auto-generated />
using System;
using Aethra.Modules.Projects.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aethra.Modules.Projects.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectsDbContext))]
    [Migration("20260602030958_SecretsTable")]
    partial class SecretsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("projects")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aethra.Modules.Projects.Domain.Clients.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("BillingTag")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("billing_tag");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_email");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("project_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_clients_project_id");

                    b.HasIndex("ProjectId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_clients_project_slug");

                    b.ToTable("clients", "projects");
                });

            modelBuilder.Entity("Aethra.Modules.Projects.Domain.EnvVars.EnvironmentVariable", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsBuildTime")
                        .HasColumnType("boolean")
                        .HasColumnName("is_build_time");

                    b.Property<bool>("IsLiteral")
                        .HasColumnType("boolean")
                        .HasColumnName("is_literal");

                    b.Property<bool>("IsMultiline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_multiline");

                    b.Property<bool>("IsRuntime")
                        .HasColumnType("boolean")
                        .HasColumnName("is_runtime");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("key");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scope_type");

                    b.Property<string>("Source")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ScopeType", "ScopeId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_env_vars_scope_key");

                    b.HasIndex("ScopeType", "ScopeId", "Source")
                        .HasDatabaseName("ix_env_vars_scope_source");

                    b.ToTable("env_vars", "projects");
                });

            modelBuilder.Entity("Aethra.Modules.Projects.Domain.Instances.Instance", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<bool>("AutoDeployOnNewBuild")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_deploy_on_new_build");

                    b.Property<string>("AutoHostname")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("auto_hostname");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_id");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("container_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomDomain")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("custom_domain");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("environment");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<string>("TargetVmId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_vm_id");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("template_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_instances_client_id");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_instances_template_id");

                    b.HasIndex("TemplateId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_instances_template_slug");

                    b.ToTable("instances", "projects");
                });

            modelBuilder.Entity("Aethra.Modules.Projects.Domain.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_projects_slug");

                    b.ToTable("projects", "projects");
                });

            modelBuilder.Entity("Aethra.Modules.Projects.Domain.Secrets.Secret", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("key");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scope_type");

                    b.Property<string>("Source")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<byte[]>("ValueCipher")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("value_cipher");

                    b.HasKey("Id");

                    b.HasIndex("ScopeType", "ScopeId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_secrets_scope_key");

                    b.HasIndex("ScopeType", "ScopeId", "Source")
                        .HasDatabaseName("ix_secrets_scope_source");

                    b.ToTable("secrets", "projects");
                });

            modelBuilder.Entity("Aethra.Modules.Projects.Domain.Templates.Template", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("project_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<byte[]>("WebhookSecretCipher")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("webhook_secret_cipher");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_templates_project_id");

                    b.HasIndex("ProjectId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_templates_project_slug");

                    b.ToTable("templates", "projects");
                });

            modelBuilder.Entity("Aethra.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt", "NextAttemptAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("outbox_messages", "projects");
                });

            modelBuilder.Entity("Aethra.Modules.Projects.Domain.Clients.Client", b =>
                {
                    b.HasOne("Aethra.Modules.Projects.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Aethra.Modules.Projects.Domain.Instances.Instance", b =>
                {
                    b.HasOne("Aethra.Modules.Projects.Domain.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aethra.Modules.Projects.Domain.Templates.Template", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Aethra.Modules.Projects.Domain.Instances.Healthcheck", "Healthcheck", b1 =>
                        {
                            b1.Property<string>("InstanceId")
                                .HasColumnType("character varying(64)");

                            b1.Property<int>("IntervalSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("hc_interval_seconds");

                            b1.Property<int>("Retries")
                                .HasColumnType("integer")
                                .HasColumnName("hc_retries");

                            b1.Property<int?>("StartPeriodSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("hc_start_period_seconds");

                            b1.Property<string>("Test")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("hc_test");

                            b1.Property<int?>("TimeoutSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("hc_timeout_seconds");

                            b1.HasKey("InstanceId");

                            b1.ToTable("instances", "projects");

                            b1.WithOwner()
                                .HasForeignKey("InstanceId");
                        });

                    b.OwnsMany("Aethra.Modules.Projects.Domain.Instances.PortMapping", "Ports", b1 =>
                        {
                            b1.Property<string>("InstanceId")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("instance_id");

                            b1.Property<int>("ContainerPort")
                                .HasColumnType("integer")
                                .HasColumnName("container_port");

                            b1.Property<int?>("HostPort")
                                .HasColumnType("integer")
                                .HasColumnName("host_port");

                            b1.Property<string>("Protocol")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("protocol");

                            b1.HasKey("InstanceId", "ContainerPort");

                            b1.ToTable("instance_ports", "projects");

                            b1.WithOwner()
                                .HasForeignKey("InstanceId");
                        });

                    b.OwnsMany("Aethra.Modules.Projects.Domain.Instances.VolumeMount", "Volumes", b1 =>
                        {
                            b1.Property<string>("InstanceId")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("instance_id");

                            b1.Property<string>("Name")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("name");

                            b1.Property<string>("ContainerPath")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("container_path");

                            b1.Property<bool>("ReadOnly")
                                .HasColumnType("boolean")
                                .HasColumnName("read_only");

                            b1.HasKey("InstanceId", "Name");

                            b1.ToTable("instance_volumes", "projects");

                            b1.WithOwner()
                                .HasForeignKey("InstanceId");
                        });

                    b.Navigation("Healthcheck");

                    b.Navigation("Ports");

                    b.Navigation("Volumes");
                });

            modelBuilder.Entity("Aethra.Modules.Projects.Domain.Templates.Template", b =>
                {
                    b.HasOne("Aethra.Modules.Projects.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Aethra.Modules.Projects.Domain.Templates.TemplateBuild", "Build", b1 =>
                        {
                            b1.Property<string>("TemplateId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("BuildArgs")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("build_args");

                            b1.Property<string>("BuildType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("build_type");

                            b1.Property<string>("ComposeFilePath")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("build_compose_file_path");

                            b1.Property<string>("DockerfilePath")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("build_dockerfile_path");

                            b1.HasKey("TemplateId");

                            b1.ToTable("templates", "projects");

                            b1.WithOwner()
                                .HasForeignKey("TemplateId");
                        });

                    b.OwnsOne("Aethra.Modules.Projects.Domain.Templates.TemplateSource", "Source", b1 =>
                        {
                            b1.Property<string>("TemplateId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("AccessTokenCredentialName")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("source_access_token_credential_name");

                            b1.Property<string>("BaseDirectory")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("source_base_directory");

                            b1.Property<string>("Branch")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("source_branch");

                            b1.Property<string>("GitRepoUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("source_git_repo_url");

                            b1.Property<string>("WatchPaths")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("source_watch_paths");

                            b1.HasKey("TemplateId");

                            b1.ToTable("templates", "projects");

                            b1.WithOwner()
                                .HasForeignKey("TemplateId");
                        });

                    b.Navigation("Build")
                        .IsRequired();

                    b.Navigation("Source")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
