// <auto-generated />
using System;
using Aethra.Modules.Projects.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aethra.Modules.Projects.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectsDbContext))]
    partial class ProjectsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("projects")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aethra.Modules.Projects.Domain.Application", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("environment_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_applications_env_slug");

                    b.ToTable("applications", "projects");
                });

            modelBuilder.Entity("Aethra.Modules.Projects.Domain.EnvVars.EnvironmentVariable", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsBuildTime")
                        .HasColumnType("boolean")
                        .HasColumnName("is_build_time");

                    b.Property<bool>("IsLiteral")
                        .HasColumnType("boolean")
                        .HasColumnName("is_literal");

                    b.Property<bool>("IsMultiline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_multiline");

                    b.Property<bool>("IsRuntime")
                        .HasColumnType("boolean")
                        .HasColumnName("is_runtime");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean")
                        .HasColumnName("is_secret");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("key");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scope_type");

                    b.Property<string>("Source")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ScopeType", "ScopeId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_env_vars_scope_key");

                    b.HasIndex("ScopeType", "ScopeId", "Source")
                        .HasDatabaseName("ix_env_vars_scope_source");

                    b.ToTable("env_vars", "projects");
                });

            modelBuilder.Entity("Aethra.Modules.Projects.Domain.Environment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_environments_project_name");

                    b.ToTable("environments", "projects");
                });

            modelBuilder.Entity("Aethra.Modules.Projects.Domain.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_projects_slug");

                    b.ToTable("projects", "projects");
                });

            modelBuilder.Entity("Aethra.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt", "NextAttemptAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("outbox_messages", "projects");
                });

            modelBuilder.Entity("Aethra.Modules.Projects.Domain.Application", b =>
                {
                    b.HasOne("Aethra.Modules.Projects.Domain.Environment", null)
                        .WithMany("Applications")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Aethra.Modules.Projects.Domain.ApplicationBuild", "Build", b1 =>
                        {
                            b1.Property<string>("ApplicationId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Path")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("build_path");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("build_type");

                            b1.HasKey("ApplicationId");

                            b1.ToTable("applications", "projects");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");

                            b1.OwnsMany("Aethra.Modules.Projects.Domain.BuildArg", "Args", b2 =>
                                {
                                    b2.Property<int>("id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("id"));

                                    b2.Property<string>("Key")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)")
                                        .HasColumnName("key");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(4000)
                                        .HasColumnType("character varying(4000)")
                                        .HasColumnName("value");

                                    b2.Property<string>("application_id")
                                        .IsRequired()
                                        .HasColumnType("character varying(64)");

                                    b2.HasKey("id");

                                    b2.HasIndex("application_id");

                                    b2.ToTable("application_build_args", "projects");

                                    b2.WithOwner()
                                        .HasForeignKey("application_id");
                                });

                            b1.Navigation("Args");
                        });

                    b.OwnsOne("Aethra.Modules.Projects.Domain.ApplicationRuntime", "Runtime", b1 =>
                        {
                            b1.Property<string>("ApplicationId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("ContainerName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("runtime_container_name");

                            b1.Property<string>("TargetVmId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("runtime_target_vm_id");

                            b1.HasKey("ApplicationId");

                            b1.ToTable("applications", "projects");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");

                            b1.OwnsOne("Aethra.Modules.Projects.Domain.Healthcheck", "Healthcheck", b2 =>
                                {
                                    b2.Property<string>("ApplicationRuntimeApplicationId")
                                        .HasColumnType("character varying(64)");

                                    b2.PrimitiveCollection<string[]>("Cmd")
                                        .IsRequired()
                                        .HasColumnType("text[]")
                                        .HasColumnName("hc_cmd");

                                    b2.Property<TimeSpan>("Interval")
                                        .HasColumnType("interval")
                                        .HasColumnName("hc_interval");

                                    b2.Property<int>("Retries")
                                        .HasColumnType("integer")
                                        .HasColumnName("hc_retries");

                                    b2.Property<TimeSpan>("StartPeriod")
                                        .HasColumnType("interval")
                                        .HasColumnName("hc_start_period");

                                    b2.Property<TimeSpan>("Timeout")
                                        .HasColumnType("interval")
                                        .HasColumnName("hc_timeout");

                                    b2.HasKey("ApplicationRuntimeApplicationId");

                                    b2.ToTable("applications", "projects");

                                    b2.WithOwner()
                                        .HasForeignKey("ApplicationRuntimeApplicationId");
                                });

                            b1.OwnsMany("Aethra.Modules.Projects.Domain.PortMapping", "Ports", b2 =>
                                {
                                    b2.Property<int>("id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("id"));

                                    b2.Property<int>("ContainerPort")
                                        .HasColumnType("integer")
                                        .HasColumnName("container_port");

                                    b2.Property<int?>("HostPort")
                                        .HasColumnType("integer")
                                        .HasColumnName("host_port");

                                    b2.Property<string>("Protocol")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("character varying(8)")
                                        .HasColumnName("protocol");

                                    b2.Property<string>("application_id")
                                        .IsRequired()
                                        .HasColumnType("character varying(64)");

                                    b2.HasKey("id");

                                    b2.HasIndex("application_id");

                                    b2.ToTable("application_runtime_ports", "projects");

                                    b2.WithOwner()
                                        .HasForeignKey("application_id");
                                });

                            b1.OwnsMany("Aethra.Modules.Projects.Domain.VolumeMount", "Volumes", b2 =>
                                {
                                    b2.Property<int>("id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("id"));

                                    b2.Property<string>("ContainerPath")
                                        .IsRequired()
                                        .HasMaxLength(1024)
                                        .HasColumnType("character varying(1024)")
                                        .HasColumnName("container_path");

                                    b2.Property<string>("HostPath")
                                        .IsRequired()
                                        .HasMaxLength(1024)
                                        .HasColumnType("character varying(1024)")
                                        .HasColumnName("host_path");

                                    b2.Property<bool>("ReadOnly")
                                        .HasColumnType("boolean")
                                        .HasColumnName("read_only");

                                    b2.Property<string>("application_id")
                                        .IsRequired()
                                        .HasColumnType("character varying(64)");

                                    b2.HasKey("id");

                                    b2.HasIndex("application_id");

                                    b2.ToTable("application_runtime_volumes", "projects");

                                    b2.WithOwner()
                                        .HasForeignKey("application_id");
                                });

                            b1.Navigation("Healthcheck");

                            b1.Navigation("Ports");

                            b1.Navigation("Volumes");
                        });

                    b.OwnsOne("Aethra.Modules.Projects.Domain.ApplicationSource", "Source", b1 =>
                        {
                            b1.Property<string>("ApplicationId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("AccessTokenId")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("source_access_token_id");

                            b1.Property<string>("BaseDirectory")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("source_base_directory");

                            b1.Property<string>("Branch")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("source_branch");

                            b1.Property<string>("GitRepoUrl")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("source_git_repo_url");

                            b1.PrimitiveCollection<string[]>("WatchPaths")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("source_watch_paths");

                            b1.Property<string>("WebhookSecret")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("source_webhook_secret");

                            b1.HasKey("ApplicationId");

                            b1.ToTable("applications", "projects");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.Navigation("Build")
                        .IsRequired();

                    b.Navigation("Runtime")
                        .IsRequired();

                    b.Navigation("Source")
                        .IsRequired();
                });

            modelBuilder.Entity("Aethra.Modules.Projects.Domain.Environment", b =>
                {
                    b.HasOne("Aethra.Modules.Projects.Domain.Project", null)
                        .WithMany("Environments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aethra.Modules.Projects.Domain.Environment", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("Aethra.Modules.Projects.Domain.Project", b =>
                {
                    b.Navigation("Environments");
                });
#pragma warning restore 612, 618
        }
    }
}
