// <auto-generated />
using System;
using Aethra.Modules.Vms.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aethra.Modules.Vms.Infrastructure.Migrations
{
    [DbContext(typeof(VmsDbContext))]
    [Migration("20260610022150_VmContainerRuntimeVersion")]
    partial class VmContainerRuntimeVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vms")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aethra.Modules.Vms.Domain.Vm", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<bool>("AcceptsPreviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("accepts_previews");

                    b.Property<string>("ContainerRuntime")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("container_runtime");

                    b.Property<string>("ContainerRuntimeVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("container_runtime_version");

                    b.Property<int?>("CpuCores")
                        .HasColumnType("integer")
                        .HasColumnName("cpu_cores");

                    b.Property<string>("CpuModel")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cpu_model");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Hostname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hostname");

                    b.Property<string>("InstallLog")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("install_log");

                    b.Property<string>("InstallStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("install_status");

                    b.Property<string>("KernelVersion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("kernel_version");

                    b.Property<DateTimeOffset?>("LastConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_connected_at");

                    b.Property<DateTimeOffset?>("LastDisconnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_disconnected_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PrivateIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("private_ip");

                    b.Property<string>("PublicIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("public_ip");

                    b.Property<long?>("RootDiskAvailableBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("root_disk_available_bytes");

                    b.Property<long?>("RootDiskTotalBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("root_disk_total_bytes");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<byte[]>("SshCredentialsCipher")
                        .HasColumnType("bytea")
                        .HasColumnName("ssh_credentials_cipher");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<long?>("TotalMemoryBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("total_memory_bytes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_vms_slug");

                    b.ToTable("vms", "vms");
                });

            modelBuilder.Entity("Aethra.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt", "NextAttemptAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("outbox_messages", "vms");
                });

            modelBuilder.Entity("Aethra.Modules.Vms.Domain.Vm", b =>
                {
                    b.OwnsOne("Aethra.Modules.Vms.Domain.Satellite", "Satellite", b1 =>
                        {
                            b1.Property<string>("VmId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("AgentVersion")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("satellite_agent_version");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("satellite_id");

                            b1.Property<DateTimeOffset?>("LastHandshakeAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("satellite_last_handshake_at");

                            b1.HasKey("VmId");

                            b1.ToTable("vms", "vms");

                            b1.WithOwner()
                                .HasForeignKey("VmId");

                            b1.OwnsOne("Aethra.Modules.Vms.Domain.SatelliteToken", "Token", b2 =>
                                {
                                    b2.Property<string>("SatelliteVmId")
                                        .HasColumnType("character varying(64)");

                                    b2.Property<string>("Hash")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)")
                                        .HasColumnName("satellite_token_hash");

                                    b2.Property<DateTimeOffset>("RotatedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("satellite_token_rotated_at");

                                    b2.HasKey("SatelliteVmId");

                                    b2.HasIndex("Hash")
                                        .HasDatabaseName("ix_vms_satellite_token_hash");

                                    b2.ToTable("vms", "vms");

                                    b2.WithOwner()
                                        .HasForeignKey("SatelliteVmId");
                                });

                            b1.Navigation("Token")
                                .IsRequired();
                        });

                    b.Navigation("Satellite")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
