// <auto-generated />
using System;
using Aethra.Modules.Metrics.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aethra.Modules.Metrics.Infrastructure.Migrations
{
    [DbContext(typeof(MetricsDbContext))]
    partial class MetricsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("metrics")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aethra.Modules.Metrics.Domain.ContainerSnapshotRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<int>("ContainerCount")
                        .HasColumnType("integer")
                        .HasColumnName("container_count");

                    b.Property<string>("ContainersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("containers");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("VmId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("vm_id");

                    b.HasKey("Id");

                    b.HasIndex("VmId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_container_snapshots_vm_time");

                    b.ToTable("container_snapshots", "metrics");
                });

            modelBuilder.Entity("Aethra.Modules.Metrics.Domain.VmMetricRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<double>("CpuPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("cpu_percent");

                    b.Property<string>("DisksJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("disks");

                    b.Property<double>("LoadAverage1")
                        .HasColumnType("double precision")
                        .HasColumnName("load_1");

                    b.Property<double>("LoadAverage15")
                        .HasColumnType("double precision")
                        .HasColumnName("load_15");

                    b.Property<double>("LoadAverage5")
                        .HasColumnType("double precision")
                        .HasColumnName("load_5");

                    b.Property<long>("MemoryFreeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("mem_free");

                    b.Property<long>("MemoryTotalBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("mem_total");

                    b.Property<long>("MemoryUsedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("mem_used");

                    b.Property<long>("NetBytesReceived")
                        .HasColumnType("bigint")
                        .HasColumnName("net_bytes_rx");

                    b.Property<long>("NetBytesSent")
                        .HasColumnType("bigint")
                        .HasColumnName("net_bytes_tx");

                    b.Property<long>("NetPacketsReceived")
                        .HasColumnType("bigint")
                        .HasColumnName("net_packets_rx");

                    b.Property<long>("NetPacketsSent")
                        .HasColumnType("bigint")
                        .HasColumnName("net_packets_tx");

                    b.Property<long>("SwapTotalBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("swap_total");

                    b.Property<long>("SwapUsedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("swap_used");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<double>("UptimeSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("uptime_seconds");

                    b.Property<string>("VmId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("vm_id");

                    b.HasKey("Id");

                    b.HasIndex("VmId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_vm_metrics_vm_time");

                    b.ToTable("vm_metrics", "metrics");
                });

            modelBuilder.Entity("Aethra.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt", "NextAttemptAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("outbox_messages", "metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
